<?php
	$title = 'Ajouter une nouvelle valise';
	$this->headTitle($title);
?>
	<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/overcast/jquery-ui.css" />
	<script src="http://code.jquery.com/jquery-1.9.1.js"></script>
	<script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
	
	<script>
		$(function() {
			$('dl.zend-form dd, input.datepick').each(function(){
				var date = $(this).datepicker({ dateFormat: 'yy-mm-dd' }).val();
			});
		});
  	</script>
  	<script type="text/javascript">
			$(function() {		
    			var id_v = <?php echo $this->id;?>;
				$('input#voyages_id').val(id_v);
		});
	</script>
	<h1><?php echo $this->escapeHtml($title); ?></h1>
		<?php
		$form = $this->form;
		$form->prepare();
		$form->setAttribute('action', $this->url('valise', array('action' => 'add', 'id'=> $this->id)));
		$form->setAttribute('method', 'post');
		echo $this->form()->openTag($form);?>
		<dl class='zend_form'/>
			<?php echo $this->formElementErrors($form->get('id')); 
			echo $this->formHidden($form->get('id'));
			echo $this->formHidden($form->get('voyages_id'));?>

        	<dt><?php echo $this->formLabel($form->get('nom_proprietaire')) ?></dt>
        	<dd><?php echo $this->formInput($form->get('nom_proprietaire')) ?></dd>
		
		<dd><?php echo $this->formSubmit($form->get('submit')) ?></dd>
		</dl>			
		<?php echo $this->form()->closeTag(); ?>

