<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('CoolTravelling')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        
                        ->prependStylesheet($this->basePath() . '/css/cool.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                        ->prependStylesheet($this->basePath() . '/css/jquery-ui.css')
                         ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                    ->prependFile($this->basePath() . '/js/jquery-ui.js')
                                    ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                    ->prependFile($this->basePath() . '/js/jquery-1.9.1.js')
                                    ->prependFile($this->basePath() . '/js/jquery.min.js')?>


    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="<?php echo $this->url('home') ?>">CoolTravelling</a>
                    <div class="nav-collapse collapse">
                        <ul class="nav">
                            <li class="active"><a href="<?php echo $this->url('home') ?>">Accueil</a></li>
                        </ul>
                        <?php if($this->zfcUserIdentity()): ?>
                        <ul class="nav pull-right">
                            <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <?php echo $this->zfcUserDisplayName() ?> 
                                <b class="caret"></b>
                            </a>
                                <ul class="dropdown-menu">
                                  <li><a href="<?php echo $this->url('zfcuser/profile')?>">Profile</a></li>
                                  <li class="divider"></li>
                                  <li><a href="<?php echo $this->url('zfcuser/logout')?>" >Déconnexion</a></li>   
                                </ul>
                            </li>
                            <li class="divider-vertical"></li>
                            <li><a href="<?php echo $this->url('voyage')?>">Mes Voyages</a></li>
                            <li><a href="#">Mon Carnet</a></li>
                        </ul>
                        <?php endif?>
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>CoolTravelling &copy; Tous droits réservés</p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>