<div class="hero-unit">
  
  <img class="image" src= "img/coollogo.png"/>
        <h1>Préparez votre voyage en deux clic !</h1>
        <h2>Selin est une super jolie fille</h2>
  <p>Organisez votre voyage dans tous ses aspects !</p>
  <p>
    <a class="btn btn-success btn-large" href="/user/login">
      S'identifier
    </a>
    <a class="btn btn-primary btn-large" href="user/register">
      Inscrivez-vous
    </a>
</p>
 
</div>

<div class="row">

    <div class="span4" id="vert">
        <h2>A propos de CoolTravelling</h2>
        <p>Ici doit etre modifiable par l'administrateur !!!!!!! COool COool COool COoolCOool COoolC OoolCO oolCOool COool COoolCOoo lCOoolC OoolCOo olCOool COoolCOool COoolC OoolCO oolCOool COool COoolCO ool COoolC OoolCOoolC OoolCOo olCOoo COool COool</p>
        <p><a class="btn btn-inverse" href="http://framework.zend.com/zf2" target="_blank">Apprenez plus &raquo;</a></p>
    </div>

    <div class="span4" id"jaune">
        <h2>Contactez-nous</h2>
        <p>Vous avez des questions ? Vous n'avez rien compris de notre application hein ? alors pourquoi tu nous pose pas de qestionsss !!!!!!! N'hesitez pas à nous écrire</p>
        <p><a class="btn btn-inverse" href="http://modules.zendframework.com/" target="_blank"><?php echo $this->translate('Ecrivez-nous') ?> &raquo;</a></p>
   </div>

   <div class="span4" id="rouge">
       <h2>Conditions d'utilisation</h2>
       <p>on vera</p>
       <p><a class="btn btn-inverse" href="http://webchat.freenode.net?channels=zftalk" target="_blank"><?php echo $this->translate('Voir plus de détails') ?> &raquo;</a></p>
   </div>
</div>
