<?php

$title = 'Mes Parcours';
$this->headTitle($title);
?>

<script>
  $(function() {
    $("#accordion").accordion({ collapsible: true, active: false});
    var icons = {
      header: "ui-icon-circle-arrow-e",
      activeHeader: "ui-icon-circle-arrow-s"
    };
    $( "#accordion" ).accordion({
      icons: icons
    });

    $( "#toggle" ).button().click(function() {
      if ( $( "#accordion" ).accordion( "option", "icons" ) ) {
        $( "#accordion" ).accordion( "option", "icons", null );
      } else {
        $( "#accordion" ).accordion( "option", "icons", icons );
      }
    });
  });
  </script>

<h1><?php echo $this->escapeHtml($title); ?></h1>

<a class="btn btn-small btn-primary" href="<?php echo $this->url('parcours',array('action'=>'add', 'id' => $this->idvoyage));?>"><i class="icon-plus icon-white"></i>Ajouter nouveau parcours</a>

<div id="accordion">
<?php foreach ($this->results as $result): ?>

  <h3><?php echo $result['parcours']->ville_depart ."-". $result['parcours']->ville_arrivee ;?> &raquo;</h3>
  <div>
    <strong>Date Début du parcours :</strong>
      <p><?php echo $result['parcours']->date_debut;?></p>
    <strong>Date Fin du parcours :</strong>
      <p><?php echo $result['parcours']->date_fin;?></p>
    <strong>Voyage concernée :</strong>
      <p><?php echo $result['voyages']->nom_voyages;?></p>
   <!-- Button to trigger modal -->
    <a href="#myModal" role="button" class="btn" data-toggle="modal">Météo</a>
     
    <!-- Modal -->
    <div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">Météo</h3>
      </div>
      <div class="modal-body">
      </div>
      <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Fermer</button>
      </div>
    </div>

    <a class="btn" href="<?php echo $this->url('parcours',array('action'=>'edit', 'id' => $result['parcours']->id));?>">Modifier</a>
    <a class="btn" href="<?php echo $this->url('parcours',array('action'=>'delete', 'id' => $result['parcours']->id));?>">Supprimer</a>
    
  </div>
<?php endforeach; ?>
</div>